- name: Install Python3, Docker, and Docker Compose
  hosts: tag_Name_ansible_server
  become: true
  vars:
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  tasks:
    - name: Install Python3
      apt:
        name: python3
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Add Docker GPG key (Ubuntu only)
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_distribution == "Ubuntu"
    - name: Add Docker repository (Ubuntu only)
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_distribution == "Ubuntu"
    - name: Install Docker packages (Ubuntu only)
      apt:
        name: "{{ docker_packages }}"
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Install Docker on Amazon Linux
      yum:
        name: docker
        state: latest
      when: ansible_distribution == "Amazon"
    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
