- name: Install Python3, docker and docker compose
  hosts: tag_Name_ansible_server
  become: true
  vars:
    compose_version: "v2.27.0"
    compose_arch: "{{ 'aarch64' if ansible_architecture in ['aarch64','arm64'] else 'x86_64' }}"
  tasks:
    - name: Update apt cache and install Python3 + Docker
      apt:
        name:
          - python3
          - docker.io
        state: present
        update_cache: yes
    - name: Ensure Docker is started and enabled
      systemd:
        name: docker
        state: started
        enabled: true
    - name: Ensure CLI plugins directory exists
      file:
        path: /usr/libexec/docker/cli-plugins
        state: directory
        mode: "0755"
    - name: Download docker-compose v2 plugin binary
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-linux-{{ compose_arch }}"
        dest: "/usr/libexec/docker/cli-plugins/docker-compose"
        mode: "0755"
    - name: Ensure Docker Compose v2 plugin (Ubuntu only)
      apt:
        name: docker-compose-plugin
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Install docker compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Start Docker daemon
      systemd:
        name: docker
        state: started
